SQLALCHEMY_DATABASE_URI = "mariadb+mariadbconnector://usuario:password@mariadb:3306/flask_database"
# SQLALCHEMY_DATABASE_URI = "mariadb+mariadbconnector://usuario:password@localhost:3306/flask_database"
SQLALCHEMY_TRACK_MODIFICATIONS = false
SECRET_KEY = "nAhaMNBaiJcz6H8eWR1oz1xNfFbXMReX"
DEEPSEEK_API_KEY = "cpk_145e465d6215459198b9895a7ffbf7b0.628389086c76508faebba4f6b0d1a90e.Aj37vjvBkJ3Dv79uyZe0BNCJcjR4F115"
NVD_API_KEY = "5b5e7cd2-045a-4955-abd9-5527597927b3"
GEMINI_API_KEY = "AIzaSyDxN-DnG03KV8UScpW11DvZCg06r33pfC0"
JWT_SECRET_KEY = "fuiqhliuehfiuwdhiuwhndiud78423jn"